### ISSUE TITLE
ICE error with the head of master tree

### ISSUE THREAD

**Issue by z971586668** [seahorn/clam#30]
Hi ,
I've got this ICE error when compling the head master tree,
my gcc version is 5.5.0
[ 19%] Building CXX object lib/CrabLlvm/CMakeFiles/CrabLlvmInstrumentation.dir/InsertInvariants.cc.o

c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
lib/CrabLlvm/CMakeFiles/CrabLlvmInstrumentation.dir/build.make:62: recipe for target 'lib/CrabLlvm/CMakeFiles/CrabLlvmInstrumentation.dir/InsertInvariants.cc.o' failed
make[2]: *** [lib/CrabLlvm/CMakeFiles/CrabLlvmInstrumentation.dir/InsertInvariants.cc.o] Error 4
CMakeFiles/Makefile2:1367: recipe for target 'lib/CrabLlvm/CMakeFiles/CrabLlvmInstrumentation.dir/all' failed
make[1]: *** [lib/CrabLlvm/CMakeFiles/CrabLlvmInstrumentation.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by caballa** [comment]
I'm afraid that I don't know what can cause this problem. Maybe if you run with verbose mode (e.g., `make VERBOSE=1`) we can know more. The gcc version used in travis is an old one (4.8). Not sure if that could be the problem. In any case, the `master` branch is not the default one. If you need LLVM 3.8 for some reason, then use the branch `dev`. If you don't care about the LLVM version, please use the branch `dev-llvm-5.0` which is our current development branch and it will become master pretty soon.

**Comment by caballa** [comment]
If you just want to play with crabllvm you can also download a docker image from 
https://hub.docker.com/r/seahorn/crabllvm_llvm_5.0

**Comment by z971586668** [comment]
Thank you very much for your answer.
I've changed to gcc-4.8 and extend the memory unit for my VM, the ICE problem has gone.
I am trying to use seahorn, and crab-llvm as an extra, it failed the multiple times during the compling...
I am actually still strugling with the compling of seahorn, but I think crab-llvm should no be a problem any more.

**Comment by caballa** [comment]
Let us know if you still have problems with seahorn

**Comment by agurfinkel** [comment]
It is advisable to use our docker container, both as a binary and as a build system (instead of the vm)

**Comment by z971586668** [comment]
Hi,
I am trying to install the tool using seahorn and crab-llvm
and I think there is a question related to crab-llvm
/home/ylzhang/SynthHorn/seahorn/crab-llvm/crab/lib/stats.cpp:13:26: error: no ‘void crab::CrabStats::reset()’ member function declared in class ‘crab::CrabStats’
   void CrabStats::reset () 


my g++ version is 4.8.4
and I don't think I have this error two days ago...


Could you please help me ?


All the best,
Yueling






On 4/14/2019 07:36，Arie Gurfinkel<notifications@github.com> wrote：

It is advisable to use our docker container, both as a binary and as a build system (instead of the vm)

**Comment by caballa** [comment]
I looks some mismatch between the header file `stats.hpp` and `stats.cpp` which shouldn't happen. Are you trying a fresh installation? 
At some point, `stats.hpp` changed location but cmake cache might have the old location which would explain the mismatch between `stats.hpp` and `stats.cpp`

**Comment by z971586668** [comment]
Yes, I am trying a fresh installation now,
the mismatch seems doesn't happen again.
Thank you very much !


On 4/17/2019 15:14，Jorge Navas<notifications@github.com> wrote：

I looks some mismatch between the header file stats.hpp and stats.cpp which shouldn't happen. Are you trying a fresh installation?

**Comment by z971586668** [comment]
Hi,
I am still trying to install LinearArbitrary, and there is something wrong with crab-llvm when executing the 
cmake --build . --target install.
It complains that "crab_os" is not defined, but "crab_os" is defined in the related .hpp file.
Besides crab--llvm, everything is good.
I wonder can I compile crab-llvm outside of LinearArbitrary/build and only use the result in LinearArbitrary?


Or, what I should do with a mismatch between cpp and hpp file?


Also, the dockerfile returned error, complaining about there is no "crab-llvm/CfgConfig.h"


Thank you very much!
Yueling


On 4/14/2019 07:36，Arie Gurfinkel<notifications@github.com> wrote：

It is advisable to use our docker container, both as a binary and as a build system (instead of the vm)

**Comment by z971586668** [comment]
Hi,
Here is a piece of errors when compiling crab-llvm
/home/ylzhang/SynthHorn/seahorn/crab-llvm/crab/lib/stats.cpp:13:26: error: no ‘void crab::CrabStats::reset()’ member function declared in class ‘crab::CrabStats’
   void CrabStats::reset () {
                          ^
/home/ylzhang/SynthHorn/seahorn/crab-llvm/crab/lib/stats.cpp:38:26: error: variable or field ‘Print’ declared void
   void CrabStats::Print (crab_os &OS) {
                          ^
/home/ylzhang/SynthHorn/seahorn/crab-llvm/crab/lib/stats.cpp:38:26: error: ‘crab_os’ was not declared in this scope
/home/ylzhang/SynthHorn/seahorn/crab-llvm/crab/lib/stats.cpp:38:35: error: ‘OS’ was not declared in this scope
   void CrabStats::Print (crab_os &OS) {
                                   ^




Thank you very much!
Yueling


On 4/14/2019 07:36，Arie Gurfinkel<notifications@github.com> wrote：

It is advisable to use our docker container, both as a binary and as a build system (instead of the vm)

**Comment by caballa** [comment]
What is LinearArbitrary? I googled it and found this https://github.com/GaloisInc/LinearArbitrary-SeaHorn/?

> Also, the dockerfile returned error, complaining about there is no "crab-llvm/CfgConfig.h"


LinearArbitrary seems to work on LLVM 3.6.
master branch of seahorn and crab-llvm work on 3.8 and we will move soon to 5.0.
The file CfgConfig.h does not exist in crab-llvm but it did long time ago. So I think it's trying to get an old version of crab-llvm.

**Comment by z971586668** [comment]
Yes, that's the project.
And sorry, I should not send the email to you, please ignore the following email also.
And I can compile crab-llvm perfectly, thank you very much!


Sorry for the inconvenience again.


All the best,
Yueling


On 4/18/2019 10:13，Jorge Navas<notifications@github.com> wrote：

What is LinearArbitrary? I googled it and found this https://github.com/GaloisInc/LinearArbitrary-SeaHorn/?

Also, the dockerfile returned error, complaining about there is no "crab-llvm/CfgConfig.h"
LinearArbitrary seems to work on LLVM 3.6.
master branch of seahorn and crab-llvm work on 3.8 and we will move soon to 5.0.
The file CfgConfig.h does not exist in crab-llvm but it did long time ago. So I think it's trying to get an old version of crab-llvm.

**Comment by caballa** [comment]
Btw, for seahorn and crab you can download the docker images here:

https://hub.docker.com/r/seahorn/seahorn-llvm5
https://hub.docker.com/r/seahorn/crabllvm_llvm_5.0

**Comment by z971586668** [comment]
Hi,
I am still trying to install LinearArbitrary, and there is something wrong with crab-llvm when executing the 
cmake --build . --target install.
It complains that "crab_os" is not defined, but "crab_os" is defined in the related .hpp file.
Besides crab--llvm, everything is good.
I wonder can I compile crab-llvm outside of LinearArbitrary/build and only use the result in LinearArbitrary?


Or, what I should do with a mismatch between cpp and hpp file?


Also, the dockerfile returned error, complaining about there is no "crab-llvm/CfgConfig.h"


Here is a piece of errors when compiling crab-llvm
/home/ylzhang/SynthHorn/seahorn/crab-llvm/crab/lib/stats.cpp:13:26: error: no ‘void crab::CrabStats::reset()’ member function declared in class ‘crab::CrabStats’
   void CrabStats::reset () {
                          ^
/home/ylzhang/SynthHorn/seahorn/crab-llvm/crab/lib/stats.cpp:38:26: error: variable or field ‘Print’ declared void
   void CrabStats::Print (crab_os &OS) {
                          ^
/home/ylzhang/SynthHorn/seahorn/crab-llvm/crab/lib/stats.cpp:38:26: error: ‘crab_os’ was not declared in this scope
/home/ylzhang/SynthHorn/seahorn/crab-llvm/crab/lib/stats.cpp:38:35: error: ‘OS’ was not declared in this scope
   void CrabStats::Print (crab_os &OS) {


Thank you very much!
Yueling


On 4/14/2019 07:36，Arie Gurfinkel<notifications@github.com> wrote：

It is advisable to use our docker container, both as a binary and as a build system (instead of the vm)
